
export const TODO_ADDED = "TODO_ADDED";
export const TODO_TOGGLED = "TODO_TOGGLED";
export const COLOR_SELECTED = "COLOR_SELECTED";
export const TODO_DELETED = "TODO_DELETED";
export const ALL_COMPLETED = "ALL_COMPLETED";
export const COMPLETED_CLEARED = "COMPLETED_CLEARED";
export const STATUS_FILTER_CHANGED = "STATUS_FILTER_CHANGED";
export const COLOR_FILTER_CHANGED = "COLOR_FILTER_CHANGED";
export const COLOR_FILTER_SELECTED = "COLOR_FILTER_SELECTED";
export const FETCH_TODOS_REQUEST = "FETCH_TODOS_REQUEST";
